# Chess (King-Rook vs. King) Dataset

Dataset - https://www.kaggle.com/datasets/abhinavgautam/chess-king-rook-vs-king-data-set/


In [ ]:
import numpy as np
import pandas as pd

In [16]:
chess = pd.read_csv('krkopt.data',names=[
    'White King file','White King rank','White Rook file',
    'White Rook rank','Black King file','Black King rank','optimal depth-of-win for White'],)
chess.head()

White King file  White King rank White Rook file  White Rook rank  \
0               a                1               b                3   
1               a                1               c                1   
2               a                1               c                1   
3               a                1               c                1   
4               a                1               c                2   

  Black King file  Black King rank optimal depth-of-win for White  
0               c                2                           draw  
1               c                2                           draw  
2               d                1                           draw  
3               d                2                           draw  
4               c                1                           draw

In [17]:
chess.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28056 entries, 0 to 28055
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   White King file                 28056 non-null  object
 1   White King rank                 28056 non-null  int64 
 2   White Rook file                 28056 non-null  object
 3   White Rook rank                 28056 non-null  int64 
 4   Black King file                 28056 non-null  object
 5   Black King rank                 28056 non-null  int64 
 6   optimal depth-of-win for White  28056 non-null  object
dtypes: int64(3), object(4)
memory usage: 1.5+ MB


In [18]:
# Label encoding categorical columns
from sklearn.preprocessing import LabelEncoder
categorical_cols = ['White King file','White Rook file','Black King file','optimal depth-of-win for White']
chess[categorical_cols] = chess[categorical_cols].apply(LabelEncoder().fit_transform)
chess.head()

White King file  White King rank  White Rook file  White Rook rank  \
0                0                1                1                3   
1                0                1                2                1   
2                0                1                2                1   
3                0                1                2                1   
4                0                1                2                2   

   Black King file  Black King rank  optimal depth-of-win for White  
0                2                2                               0  
1                2                2                               0  
2                3                1                               0  
3                3                2                               0  
4                2                1                               0

In [19]:
# Setting predictor and target variables 
X = chess.drop('optimal depth-of-win for White',axis=1)
y = chess['optimal depth-of-win for White']

In [20]:
# Splitting data into training and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
# Instantiating Model
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
# Fitting data
rfc.fit(X_train,y_train)

DecisionTreeClassifier()

In [22]:
# Predicting Data
y_pred = rfc.predict(X_test)

In [23]:
# Model evaluation 
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print('Accurany Score:',accuracy_score(y_test,y_pred))
print('Confusion Matrix:\n',confusion_matrix(y_test,y_pred))
print('Classification Report:\n',classification_report(y_test,y_pred))

Accurany Score: 0.8467569493941554
Confusion Matrix:
 [[464   8  18  13   2   1  23   2   0   4   0   8  14  16   0  14   2   1]
 [  8 226   2   0   1   0   0  15   0   5   2   0   5   4   0   3   0   0]
 [  9   3 496   0   0   0   1   5   0   0   0   0  22   4   0  31   0   0]
 [ 11   0   0 382   0   0  34   0   0   0   0  10   0   2   0   0   0   0]
 [  0   0   1   1  74   0   0   1   0   1   2   0   0   0   0   0   0   0]
 [  1   1   0   0   0  39   0   0   0   0   0   0   0   0   2   0   0   0]
 [ 11   0   4  32   0   0 804   0   0   0   0   1   2  53   0   2   0   0]
 [  5  12  13   0   2   0   0 276   1   2   0   1  17   0   0   2   0   0]
 [  0   0   0   0   0   0   0   0  10   1   0   0   0   0   0   0   0   0]
 [  7  17   1   0   0   0   0   4   0 125   7   0   0   0   0   3   0   0]
 [  1   0   0   0   3   0   0   4   0   8 105   0   0   0   0   0   0   0]
 [  7   0   0   6   0   0   2   0   0   0   0  54   0   0   0   0   0   0]
 [  8   3  44   0   1   0   2  21   0   2   0 