# Social Networking Ads - SVC

In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [35]:
dataset = pd.read_csv('./Social_Network_Ads.csv')
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

## Splitting the dataset into target and predictor variables

In [36]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

## Splitting the dataset into training and testing set


In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=1/4,random_state=0)

## Feature Scaling

In [38]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Training the model (Linear Kernel)

In [39]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(X_train,y_train)

SVC(kernel='linear')

## Predicting the result

### Predicting test results

In [40]:
y_pred = svc.predict(X_test)

### Predicting result

In [41]:
svc.predict(scaler.transform([[43,90000]]))

array([1], dtype=int64)

## Evaluating the model

In [42]:
from sklearn.metrics import classification_report, confusion_matrix
print(f"Confusion Matrix:\n {confusion_matrix(y_test,y_pred)}")
print(f"Classification Report:\n {classification_report(y_test,y_pred)}")

Confusion Matrix:
 [[66  2]
 [ 8 24]]
Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.97      0.93        68
           1       0.92      0.75      0.83        32

    accuracy                           0.90       100
   macro avg       0.91      0.86      0.88       100
weighted avg       0.90      0.90      0.90       100



## Training the Model (RBF Kernel)

In [43]:
classifier = SVC(kernel='rbf')
classifier.fit(X_train,y_train)

SVC()

## Making Predictions

In [44]:
y_pred = classifier.predict(X_test)

## Evaluating the model

In [45]:
from sklearn.metrics import classification_report, confusion_matrix
print(f"Confusion Matrix:\n {confusion_matrix(y_test,y_pred)}")
print(f"Classification Report:\n {classification_report(y_test,y_pred)}")

Confusion Matrix:
 [[64  4]
 [ 3 29]]
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.94      0.95        68
           1       0.88      0.91      0.89        32

    accuracy                           0.93       100
   macro avg       0.92      0.92      0.92       100
weighted avg       0.93      0.93      0.93       100

